apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hdgqkn9vc-nodejs
  janus-idp.io/tekton: hdgqkn9vc-nodejs
  backstage.io/kubernetes-id: hdgqkn9vc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hdgqkn9vc-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
